export const fontOptions = [
    { value: 'Poppins', label: 'Poppins' },
    { value: 'Montserrat', label: 'Montserrat' },
    { value: 'Lato', label: 'Lato' },
    { value: 'Roboto', label: 'Roboto' },
    { value: 'Open Sans', label: 'Open Sans' },
    { value: 'Quicksand', label: 'Quicksand' },
    { value: 'Playfair Display', label: 'Playfair Display' },
    { value: 'Nunito', label: 'Nunito' },
    { value: 'Raleway', label: 'Raleway' },
    { value: 'Source Sans Pro', label: 'Source Sans Pro' },
    { value: 'Oswald', label: 'Oswald' },
    { value: 'Roboto Condensed', label: 'Roboto Condensed' },
    { value: 'Ubuntu', label: 'Ubuntu' },
    { value: 'Merriweather', label: 'Merriweather' },
    { value: 'Dancing Script', label: 'Dancing Script' },
    { value: 'Fira Sans', label: 'Fira Sans' },
    { value: 'Work Sans', label: 'Work Sans' },
    { value: 'Inter', label: 'Inter' },
    { value: 'Exo', label: 'Exo' },
    { value: 'Archivo', label: 'Archivo' },
    { value: 'Rubik', label: 'Rubik' },
    { value: 'Lora', label: 'Lora' },
    { value: 'Josefin Sans', label: 'Josefin Sans' },
    { value: 'Pacifico', label: 'Pacifico' },
    { value: 'Noto Sans', label: 'Noto Sans' },
    { value: 'Muli', label: 'Muli' },
    { value: 'Cabin', label: 'Cabin' },
    { value: 'Hind', label: 'Hind' },
    { value: 'Manrope', label: 'Manrope' },
    { value: 'Lalezar', label: 'Lalezar' },
]